import React from 'react';


export const Chart7 = () => {
  return (
    <div className="门店排名 bordered">
      <h2>客流峰值分析</h2>
      <div className="rank">
        <table>
          <thead>
          <tr>
            <th>排名</th>
            <th>门店名称</th>
            <th>销售额</th>
            <th>订单数</th>
            <th>客单价</th>
            <th>客流量</th>
            <th>提袋数</th>
            <th>巡店考核评分</th>
            <th>问题数</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>1</td>
            <td>每日明生广场店</td>
            <td>929.00元</td>
            <td>15</td>
            <td>49.03元</td>
            <td>480</td>
            <td>16.08%</td>
            <td>86.4</td>
            <td>8</td>
          </tr>
          <tr>
            <td>1</td>
            <td>每日明生广场店</td>
            <td>929.00元</td>
            <td>15</td>
            <td>49.03元</td>
            <td>480</td>
            <td>16.08%</td>
            <td>86.4</td>
            <td>8</td>
          </tr>
          <tr>
            <td>1</td>
            <td>每日明生广场店</td>
            <td>929.00元</td>
            <td>15</td>
            <td>49.03元</td>
            <td>480</td>
            <td>16.08%</td>
            <td>86.4</td>
            <td>8</td>
          </tr>
          <tr>
            <td>1</td>
            <td>每日明生广场店</td>
            <td>929.00元</td>
            <td>15</td>
            <td>49.03元</td>
            <td>480</td>
            <td>16.08%</td>
            <td>86.4</td>
            <td>8</td>
          </tr>
          <tr>
            <td>1</td>
            <td>每日明生广场店</td>
            <td>929.00元</td>
            <td>15</td>
            <td>49.03元</td>
            <td>480</td>
            <td>16.08%</td>
            <td>86.4</td>
            <td>8</td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};