import React from 'react';


export const Chart7 = () => {
  return (
    <div className="bordered 门店排名">
      <h2>客流峰值分析</h2>
      <div className="rank">
        <table>
          <thead>
          <tr>
            <th>排名</th>
            <th>门店名称</th>
            <th>销售额</th>
            <th>订单数</th>
            <th>客单价</th>
            <th>客流量</th>
            <th>提袋数</th>
            <th>巡店考核评分</th>
            <th>问题数</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <th>1</th>
            <th>每日明生广场店</th>
            <th>929.00元</th>
            <th>15</th>
            <th>49.03元</th>
            <th>480</th>
            <th>16.08%</th>
            <th>86.4</th>
            <th>8</th>
          </tr>
          <tr>
            <th>1</th>
            <th>每日明生广场店</th>
            <th>929.00元</th>
            <th>15</th>
            <th>49.03元</th>
            <th>480</th>
            <th>16.08%</th>
            <th>86.4</th>
            <th>8</th>
          </tr>
          <tr>
            <th>1</th>
            <th>每日明生广场店</th>
            <th>929.00元</th>
            <th>15</th>
            <th>49.03元</th>
            <th>480</th>
            <th>16.08%</th>
            <th>86.4</th>
            <th>8</th>
          </tr>
          <tr>
            <th>1</th>
            <th>每日明生广场店</th>
            <th>929.00元</th>
            <th>15</th>
            <th>49.03元</th>
            <th>480</th>
            <th>16.08%</th>
            <th>86.4</th>
            <th>8</th>
          </tr>
          <tr>
            <th>1</th>
            <th>每日明生广场店</th>
            <th>929.00元</th>
            <th>15</th>
            <th>49.03元</th>
            <th>480</th>
            <th>16.08%</th>
            <th>86.4</th>
            <th>8</th>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};